/*
COUNTRY PHONE NUMBER
*/

SELECT C.CUSTOMER_ID  , C.NAME  , CONCAT( "+",COC.COUNTRY_CODE,C.PHONE_NUMBER  )

FROM CUSTOMERS C
LEFT JOIN ON COUNTRY_CODES COC ON C.COUNTRY = COC.COUNTRY
;

/*
PROFITABLE STOCKS
*/
SELECT PT.STOCK_CODE 
FROM PRICE_TODAY PT
INNER JOIN PRICE_TOMORROW PTO ON PT.STOCK_CODE = PTO.STOCK_CODE 
WHERE PT.PRICE < PTO.PRICE
ORDER BY PT.STOCK_CODE
;